CREATE DATABASE INSTRUCTION_OF_DB DEFAULT CHARACTER SET UTF8;
SHOW DATABASES;
USE INSTRUCTION_OF_DB;

SELECT * FROM ORDER_LIST;


ALTER TABLE PRODUCT ADD CONSTRAINT CHECK(STOCK >= 0 AND STOCK<=10000);

SELECT * FROM CUSTOMER;
SELECT * FROM PRODUCT;
SELECT * FROM ORDER_LIST;

SELECT DISTINCT COMPANY
FROM PRODUCT;

SELECT PRODUCT_NAME, PRICE AS DOLLAR FROM PRODUCT;

DROP TABLE ORDER_LIST;

SELECT PRODUCT, CNT, ORDER_DATE
FROM ORDER_LIST
WHERE CUSTOMER = 'APPLE' OR CNT>= 15;

SELECT CUSTOMER_NAME, AGE, GRADE
FROM CUSTOMER
WHERE CUSTOMER_NAME LIKE 'K%';

SELECT ID, CUSTOMER_NAME, GRADE
FROM CUSTOMER
WHERE ID LIKE '_____';

SELECT CUSTOMER_NAME
FROM CUSTOMER
WHERE AGE IS NULL;

SELECT CUSTOMER_NAME, GRADE, AGE
FROM CUSTOMER
ORDER BY AGE DESC;

SELECT CUSTOMER, PRODUCT, CNT, ORDER_DATE
FROM ORDER_LIST
ORDER BY PRODUCT ASC, CNT DESC;

SELECT PRODUCT
FROM ORDER_LIST;


SELECT SUM(PRICE) AS SUM
, AVG(PRICE) AS AVG
, MIN(PRICE) AS MIN
, MAX(PRICE) AS MAX
, COUNT(PRICE) AS CNT
FROM PRODUCT;

SELECT COUNT(ID), COUNT(AGE)
FROM CUSTOMER;

SELECT SUM(CNT) AS COUNT
FROM ORDER_LIST
GROUP BY PRODUCT;

SELECT COMPANY, COUNT(*) AS PRODUCT_CNT, MAX(PRICE) AS MAX_PRICE
FROM PRODUCT
GROUP BY COMPANY;

SELECT COMPANY, COUNT(*) AS PRODUCT_CNT, MAX(PRICE) AS MAX_PRICE
FROM PRODUCT
GROUP BY COMPANY HAVING COUNT(*) >= 3;

SELECT PRODUCT, CUSTOMER, CNT
FROM ORDER_LIST
GROUP BY PRODUCT, CUSTOMER;

SELECT PRODUCT.PRODUCT_NAME
FROM PRODUCT, CUSTOMER, ORDER_LIST
WHERE ORDER_LIST.ORDER_CUSTOMER = ‘banana’ AND PRODUCT.NUM = ORDER_LIST.ORDER_PRODUCT;

SELECT *
FROM ORDER_LIST
WHERE ORDER_CUSTOMER = ‘carrot’;

SELECT *
FROM ORDER_LIST
WHERE ADDRESS = 'seoul_mapo';

SELECT ORDER_PRODUCT, ORDER_DATE
FROM CUSTOMER AS C, ORDER_LIST AS O
WHERE C.AGE >= 30
AND C.ID = O.ORDER_CUSTOMER;

SELECT PRODUCT_NAME, PRICE
FROM PRODUCT
WHERE COMPANY = (SELECT COMPANY
				FROM PRODUCT
                WHERE PRODUCT_NAME = 'BISCUIT');
                
SELECT CUSTOMER_NAME, POINT
FROM CUSTOMER
WHERE POINT = (SELECT MAX(POINT) FROM CUSTOMER);

SELECT  PRODUCT_NAME, COMPANY
FROM PRODUCT
WHERE NUM IN('p01', 'p04','p06');

SELECT PRODUCT_NAME, PRICE, COMPANY
FROM PRODUCT
WHERE PRICE > ALL (SELECT PRICE
				FROM PRODUCT
                WHERE COMPANY = 'DAEHAN');

SELECT *
FROM PRODUCT
WHERE EXISTS(SELECT *
			FROM ORDER_LIST
            WHERE ADDRESS LIKE 'KUNGGIDO%'
				AND ORDER_LIST.ORDER_PRODUCT = PRODUCT.NUM);

SELECT *
FROM PRODUCT
WHERE NUM IN (SELECT *
			FROM ORDER_LIST
            WHERE ADDRESS LIKE 'KUNGGIDO%'
				AND ORDER_LIST.ORDER_PRODUCT = PRODUCT.NUM);

INSERT
INTO CUSTOMER(ID, CUSTOMER_NAME, AGE, GRADE, JOB, POINT)
VALUES ('MANGGO', 'LIM', 19, 'VIP', 'STUDENT', 7000);

CREATE VIEW VIPS(ID, CUSTOMER_NAME, AGE)
AS SELECT ID, CUSTOMER_NAME, AGE
	FROM CUSTOMER
	WHERE GRADE = "VIP"
WITH CHECK OPTION;

CREATE VIEW COMP_CNT(COMPANY, CNT)
AS SELECT COMPANY, COUNT(*)
	FROM PRODUCT
    GROUP BY COMPANY;

INSERT INTO COMP_CNT VALUES (‘BI’, 0);


SELECT * FROM PRODUCT;